#!/usr/bin/env perl

use warnings;
use strict;

my @hindi_artists = (
    'Yasser Desai',
    'Sonu Nigam',
    'Rahat Fateh Ali Khan',
    'Mohit Chauhan',
    'K K',
    'Kishore Kumar',
    'Armaan Malik',
    'Arijit Singh',
    'Ankit Tiwari',
    'Ali Sethi'
    );

unless (@ARGV) { die "No files." }

foreach my $file_name (@ARGV) {
    unless ($file_name =~ m/.mp3$/) { next }
    my ($name) = $file_name =~ /(.*).mp3/;
    my ($_title, $artist) = split(" - ", $name);
    my $genre = "Punjabi";
    if (grep m/^$artist$/, @hindi_artists) {
        $genre = "Hindi";
    }
    if ($artist) {
        system("mid3v2 -c $genre '" . $file_name . "'");
        print $file_name . " => " . $genre . "\n";
    }
}
